spring.application.name=job-tracker

spring.datasource.url=jdbc:postgresql://localhost:5433/job_tracker
spring.datasource.username=job_tracker_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000